### ISSUE TITLE
Distinguishing Tag86 in MT940

### ISSUE THREAD

**Issue by ingridgoh** [prowide/prowide-core#166]
Hi team,

I'd like to know how I can distinguish the two kinds of tag86 in MT940 messages. Is there a way that I can reference the tags by their index no.? I'm currently using `b4.getFieldsByNumber(86)` to extract the tags and they're are conflated into one.

![image](https://github.com/prowide/prowide-core/assets/6029239/e1e33121-aa21-4fb6-a725-5ccf02e92088)

**Comment by zubri** [comment]
Notice field 62a is mandatory so it will always be present in a valid message structure. Thus if you rely on that field as a separator, you know that field 86 after the 62a, if present, is the last one. And any other field 86 before that is part of the repetitive loop.

Then for implementation, you have many options. Check the getSubBlock methods in the SwiftTagListBlock:

https://www.javadoc.io/doc/com.prowidesoftware/pw-swift-core/latest/com/prowidesoftware/swift/model/SwiftTagListBlock.html

You could for example first check if the message contains field 62F or field 62M (since both letter options are available). Then you can get that field index and capture the fields 86 before and after the index. 
You can also get the sunblock before the first field 62M or 62F, and from that sub block get all fields 86s. 
Etc...
