### ISSUE TITLE
Upgrade from 7.3 to 7.10.3 - Field87C disappeared - How to generate it?

### ISSUE THREAD

**Issue by andregasser** [prowide/prowide-core#18]
Hi there,

We're currently using Prowide Core (WIFE) 7.5 and want to upgrade to version 7.10.3 (latest release). While working on this, I've recognized that a field that we use for message generation (class Field87C) is no longer existent in the latest release. Is there a possibility that I still can generate this field and send it in a SWIFT message generated by Prowide Core?

First, I thought it would be possible using 

`public static Field getField(java.lang.String name, java.lang.String value)`

But the fact that this method returns a specialized instance of Field class is not really helpful, as Field87C is no more existent.

Any idea on how I could solve my problem?

Best regards,
André

**Comment by zubri** [comment]
Hi,

Version 7.3 is quite old. Notice we release new versions each year including the updated SWIFT SRU. So each year some message structures change and with that, some fields are removed, others are changed and some are added.

Depending on your use case, you have several ways to deal with the lack of a specific FieldNN class. 
If you are parsing a message with field 87C you can use the backbone model layer to get the message as a Tag object, and then parse the internal structure yourself. That means getting the SwiftMessage, then the SwiftBlock4 and then getTagByName. If Field 87C shares the internal structure with another current field, you can even pass the tag value to another "compatible" field in order to get the internal components parsed.
Analogously when creating a new message, you won't have the Field87C to create a field instance, but you can always create a plain Tag("87C", formattedValue) and append it to the message.

Take a look at https://www.prowidesoftware.com/resources/SWIFT-model

**Comment by andregasser** [comment]
Hi Zubri,

Thanks for your reply. It works the way you described. Problem solved from my side.

Best regards,
André
