### ISSUE TITLE
Issue with Austraclear payments

### ISSUE THREAD

**Issue by Hawk-360** [prowide/prowide-core#24]
Hi,

Recently updated to 10.3, previously we were able to process payments MT198_027 from Austraclear (Australian clearing ) but after upgrade we are facing issue with parsing of 3 digit tags.
Payment sample : 
{1:F01ZYXWAUFFFXXX5267848975}{2:O1981503161229ABCDAUFFFXXX51777922521612291503N}{3:{108:EEEEE0093090}}{4:
:20:GBM27E272BQ06
:12:027
:77E:
:21:270259BQ06
**:905:NATA**
:25:182-182-010091282
:32A:171122AUD259
**:901:150254
:908:ACLR**
:113:ADA                          
-}

Now Parsed tag 21 contains tag 905 similarly 32A has 901 and 908, which later results in processing failure.

Looking at Swiftparser.java --> tagStart() method it looks like we only support tags with no character options (dd) and tags with letter option (ddc). 

Please assist.
thanks.

**Comment by zubri** [comment]
Yes, that change was necessary in order to allow the colon as the first character in multi-line fields, which is valid for compliant messages.

In order to parse your message, you could inherit the SwiftParser overriding the method
	boolean tagStarts(final String s, int i)

That method is private final in the 10.3 release, but protected in the 10.4 snapshot source code.
