### ISSUE TITLE
Incorrect parsing of field 77E in MTn98

### ISSUE THREAD

**Issue by SebastianGedin** [prowide/prowide-core#27]
There seems to be a bug when parsing proprietary messages. Lines starting with a SWIFT tag inside the proprietary message are interpreted as their own fields rather than as part of field 77E. According to the SWIFT standard one should be allowed to use SWIFT tags inside field 77E.

With the following code I would expect fields 21 and 11S to be be inside field 77E, but they are interpreted at separate fields after 77E (see attached picture).

```java
private static void parseMT298() throws IOException {
    String message = "{1:F01XXXXXXXXXXXX1746132598}{2:O2981817450530XXXXXXXXXXXX27490070701205301807N}{4:\r\n" +
            ":20:1708092\r\n" +
            ":12:550\r\n" +
            ":77E:\r\n" +
            ":21:FIELD21CONTENT\r\n" +
            ":11S:103\r\n" +
            "190528\r\n" +
            "-}{5:{TNG:}}";
    SwiftMessage swiftMessage = new SwiftParser(message).message();
    AbstractMT abstractMT = AbstractMT.create(swiftMessage.getTypeInt());
    abstractMT.setSwiftMessage(swiftMessage);

    MT298 mt298 = (MT298) abstractMT;
}
```

![swift-prowide-bug](https://user-images.githubusercontent.com/17001936/60875674-a31e8500-a23a-11e9-9c32-45be80d9849a.PNG)

**Comment by SebastianGedin** [comment]
This seems to be intended behavior.

**Comment by zubri** [comment]
Yes, it is the intended behavior. 

We parse the 77E as field with empty value. When processing the message you can treat it as a boundary separator for the following proprietary collection of fields. Then each field following the 77E can be parsed with the standard field classes. 

This is intentional to share a common model and parse logic for all fields. The text block model for all message types is an ordered list of fields; what varies from one MT to the other is just the order and repetition of the fields that are allowed.
