### ISSUE TITLE
Problem with parsing Field59

### ISSUE THREAD

**Issue by slachiewicz** [prowide/prowide-core#29]
For sample string passed to constructor of Field59

```
PL123
CO LTD
BUSINESS PARK,
ROAD,
OXFORD, UNITED KINGDOM
````
i got warning:
```May 15, 2020 4:03:35 PM com.prowidesoftware.swift.model.field.Field setComponent
WARNING: component number 6 is out of bound for field 59
```
where field `PARSER_PATTERN ="[/S$]S[$S]0-3"`

**Comment by zubri** [comment]
If the first line in your field is the account number it should be prepended by a slash. So that it is parsed into component [/S$]

Without the starting slash, the parser will assume the first optional component is not present, so the whole set of lines is parsed into the name & address components, that is expected to receive 4 lines at most: S[$S]0-3.

Since all parsers in the library are lenient, your extra line is still parsed into an invalid component 6, with the warning.

**Comment by slachiewicz** [comment]
yes, thx.
