### ISSUE TITLE
MT parser does not split a multiline field into components with last version SRU2020-9.1.2

### ISSUE THREAD

**Issue by fidel-abascal** [prowide/prowide-core#40]
Hello there,

Having the following field70 inside a String mt103 fin message:
```
":70:/ROC/E2EId1232341\n" +
"/RFB/Remittance information\n" +
```
After parsing into a MT103 object, the field does not have different components but it have different lines. Also, function `getValueByCodeword` retrieves concatenated lines instead desired line value.

**Version**
I'm facing this issue with last version `SRU2020-9.1.2` (working as expceted with `SRU2019-8.0.1`).

**How to reproduce**
Given a fin message with a field splitted in different lines like previous:
`MT103.parse(givenMT103Message).getField70().getValueByCodeword("ROC")` should be `E2EId1232341` but it is `E2EId1232341\n/RFB/Remittance information`.
Also `MT103.parse(givenMT103Message).getField70().getComponents().size()` should be `2` (or pre-size of `4`) but it is `1`.

_Note: getLines function works as expected. (even having components arraylist initialized with a pre-size of 4)_

**Comment by zubri** [comment]
Since version 9 we have changed the internal structure for fields 29A, 37N, 45B, 46B, 49M, 49N, 70, 71B, 71D, 72Z, 72, 73A, 73, 74, 75, 76, 77A, 77B, 77D, 77J, 77. 

The previous structure with components per line was not accurate for all cases. So we have switched to an internal structure where the whole value is stored as a **single string**, but a **new API** is provided to extract content from the value or to build new narrative fields from scratch.

Take a look at this:. 

https://www.javadoc.io/static/com.prowidesoftware/pw-swift-core/SRU2020-9.1.2/com/prowidesoftware/swift/model/field/NarrativeContainer.htm

You can get a `Narrative` object out of the field, then you can get the structured parts, and finally retrieve the complete narrative attached to a codeword **regardless of the line breaks**. The API consolidates the narrative per codeword into single joined Strings. 

Previous implementation was only useful for certain combinations of codeword per lines, and did not provide any way to simplify building this values either.
