### ISSUE TITLE
Getting a field from an MT sequence that is also present in a subsequence

### ISSUE THREAD

**Issue by patricklucas** [prowide/prowide-core#43]
In [MT548](https://www.iso20022.org/15022/uhb/finmt548.htm) optional Sequence B, there is an optional repeated field 95a Party, and in optional repetitive Subsequence B1 there is also a mandatory repeated field 95a Party.

If I first extract Sequence B from an MT548 instance using `mt548.getSequenceB()`, and then call `sequenceB.getFieldsByNumber(95)`, I am returned _all_ fields 95 from Sequence B—including those in every Subsequence B1.

What would the idiomatic way of getting just the fields 95 from strictly Sequence B? (I can reliably get the fields 95 from each B1 subsequence using `MT548.getSubsequenceB1List(sequenceB)` and calling `sequenceB1.getFieldsByNumber(95)` on each)

I'm currently working around this by using `MT548.SequenceB.START_TAG` and `MT548.SequenceB1.START_TAG` as subblock boundaries, but this doesn't seem ideal:

```java
var strictSequenceB = sequenceB.getSubBlock(MT548.SequenceB.START_TAG, MT548.SequenceB1.START_TAG);
```

**Comment by zubri** [comment]
The getSequence API returns a sub-block, including all inner sequences fields. So the getFields API on the returned sequence, by default will also retrieve the fields instances from the enclosed inner sequences. 

To get only fields in the parent retrieved sequence, you have trim the inner sequences first, so that a getField in the sub-block strictly returns fields in that parent sequence.

Check this issue and its related example. It is the same user case, in a different message type though.
https://github.com/prowide/prowide-core/issues/41

**Comment by patricklucas** [comment]
Understood, thanks.

I've switched to using `SwiftMessageUtils.removeInnerSequences()`.
