### ISSUE TITLE
Possible regression in getDescription()/getNarrative()

### ISSUE THREAD

**Issue by hypfvieh** [prowide/prowide-core#50]
Hi,

the change which introduces the [feature to pass a delimiter](https://github.com/prowide/prowide-core/commit/84b7f87afaffcc7b96422e4dc4f2f87b1ed62dfe#diff-9bd1fa09ed5151e64e3267c186173c575e9cf4aef3a51d8e833d64a55b8c31c0) to the `getNarrative`/`getDescription` methods breaks old code that relay on receiving the concatenated text with `SWIFT_EOL` as delimiter.

I noticed the issue in Field35B. When calling `field35.getDescription()`, the text is concatenated without any delimiter, because `getDescription()` calls `getDescription(null)`. 

To stay compatible with older code it would be great to change the call in `getDescription()` to `getDescription(SWIFT_EOL)`.
If someone needs another delimiter he/she should use `getDescription(delimiter)` instead of the no-args version.

**Comment by zubri** [comment]
Hi,

I understand your point. However that change was requested by other users because the implementation was already inconsistent and not honouring its javadoc. So we have applied the change as a FIX, not as breaking change driven by a feature request. 

More precisely, all those methods were always expected to do what is indicated in the javadoc, for example:

`Gets the Description as a concatenation of component 3 to component 6`

So the expected result was to do a simple concatenation, preserving the value in the components and not adding any CRLF. So if the description for the security identification 35B has two lines like this:

"FIRST LINE OF DESCRIPTION "
"SECOND LINE"

The expected result is "FIRST LINE OF DESCRIPTION SECOND LINE". Thus preserving any trailing space. 

This way the getDescription or getNarrative recreates the original content, regardless of how the lines were wrap when the field was created. Some application do wrapping by words, and others do wrapping just by the line length event if that results in a single world split by a LF.

This is also consistent with the getComponentN methods that return the component as is, without alteration.

Then as alternative method, if someone wants the trim, the getLines already does that. And if someone needs to joined lines with space or LF; then there are the new methods with the delimiter parameter.
