### ISSUE TITLE
Special sequence _A in MT940/MT942 and like

### ISSUE THREAD

**Issue by Fadelis** [prowide/prowide-core#57]
Hi, I'm trying to build a hierarchical JSON representation of MT messages similar to what's documented on MTs Javadocs, but I've noticed an edge case that for some MT's like `MT940`/`MT942` there exists a special sequence `Sequence _A`, which is document in the Javadocs, but does not have any accessors to retrieve it, like with other MTs, ie `getSequenceAList()`. Is there a specific reason for this, or would there be a possibility to add it?
https://github.com/prowide/prowide-core/blob/ff833efd7f6ada1b6ae0d62f610e882c9602c[…]erated/java/com/prowidesoftware/swift/model/mt/mt9xx/MT940.java https://github.com/prowide/prowide-core/blob/ff833efd7f6ada1b6ae0d62f610e882c9602c[…]erated/java/com/prowidesoftware/swift/model/mt/mt9xx/MT942.java

**Comment by zubri** [comment]
Hi,

Answering your question the reason why some MTXxx classes do not include the SequenceX object in the model is because in the standard those message does not define a sequence. They are references as a repetitive section with no sequence name. That's the case for example of MT201 and MT210. If you check the standard you will see:

<img width="982" alt="Screen Shot 2019-09-04 at 11 27 35" src="https://user-images.githubusercontent.com/3846086/132146305-98a744d3-66d6-4100-a141-b89381e0bc63.png">

Conversely, for example MT202COV clearly defines a sequence B as:

<img width="921" alt="Screen Shot 2019-09-04 at 11 33 31" src="https://user-images.githubusercontent.com/3846086/132146329-74171b02-788f-45c5-8761-d3aece331efe.png">

In the message structure at our javadoc, we seamlessly present the formal sequences and internal loops (not sequences in the standard). But notice the later has an underscore prefix in the sequence name. That's the case for MT201, in the javadoc you will find _B because for the standard there is no "sequence B".

All in all, in the model we have Sequence objects for formal clearly identified sequences in the standard, but not for the "internal loops" (repetitive group of fields)
