### ISSUE TITLE
supperset

### ISSUE THREAD

**Issue by philipus** [prowide/prowide-core#79]
Hi,
sorry using this channel but do you think its possible to create a superset of all iso20022 messages at least for all messages related payment and banking SWFIT 1xx - 7xx ?

**Comment by zubri** [comment]
Hi,

What do you mean? For the model? We already have a hierarchy.
Also do you mean MT o MX? Since you mentioned 1xx - 7xx which would be MT (ISO 15022), not MX (ISO20022)

Regards

**Comment by philipus** [comment]
I am wandering if I can create a data set / a set of data fields from several message types (pacs 008 004 003, pain xxx, camt xxx, ... ) which I need to screen against sanction lists. I had a look at pacs, pain, and camt messages in particular at tags and annotation and got the gut feeling thats probably not possible 

With swift messages (MT) you can do that because fields (i.e. field 50) have the same meaning across message types (i.e. mt103 mt202)

What is your perspective?!

**Comment by zubri** [comment]
Have you checked our https://github.com/prowide/prowide-iso20022 project?

We have done exactly that, a huge dictionary set for all possible elements in any current or historic ISO 20022 message. 
Instead of MT fields you have classes to represent any possible element in the ISO 20022 XMLs.

Just beware the package is huge, way bigger than the MT fields model.
