### ISSUE TITLE
Missing constants for ISO 15022 codes

### ISSUE THREAD

**Issue by sman-81** [prowide/prowide-core#88]
I have come across a number of Swift ISO 15022 codes for which no constants exist in the `com.prowidesoftware.swift.SchemeConstants*` classes.
I assume my list is far from complete. These codes are only the ones I found missing when I required them in some application code:

- `ACTU`
- `APMT`
- `BUYI`
- `CANI`
- `DECU`
- `DELI`
- `DVCA`
- `DVOP`
- `FAMT`
- `FREE`
- `ISIN`
- `PART`
- `PRCT`
- `PSET`
- `RECE`
- `RECU`
- `UNIT`
- `WITF`

The SchemeConstants* classes are generated code.
Does the data source for the generator contain descriptive information, as seen [here](http://www.iotafinance.com/en/SWIFT-ISO15022-Message-Codes.html)?
If so, could the generator be enhanced to create Javadoc from these descriptions of the constants?

The generator itself is not part of `pw-swift-core` and possibly closed source. If I am given access, I could look into this enhancement and a pull request.

**Comment by zubri** [comment]
Yes, the constants are partial. What is covered is the main codewords used in the fields definitions. Such as:

![Screen Shot 2022-01-05 at 12 56 26](https://user-images.githubusercontent.com/3846086/148248337-2dd8f464-0264-4391-a9c9-aafd1e599e37.png)

It was original intended for traceability in tests. But since it appears to have more value, we will extend its coverage in the code generation to have more (all if possible).

----

Regarding descriptions have you checked this https://github.com/prowide/prowide-core/blob/84c9e7e814fce08e536026b79695edb7df053f2b/src/main/resources/pw_swift_labels_en.properties#L655 ?

The property file contains the labels for the qualifiers applied to each specific field (and in some cases specific MT).
And it is used by the getLabel methods in the Field classes.

**Comment by zubri** [comment]
Added in [SRU2022-9.3.6](https://github.com/prowide/prowide-core/releases/tag/SRU2022-9.3.6)
