### ISSUE TITLE
Make Field methods non-final to allow subclassing

### ISSUE THREAD

**Issue by sman-81** [prowide/prowide-core#95]
Subclasses of `com.prowidesoftware.swift.model.field.Field` have a few final methods that prevent subclassing.
Can we make these methods non-final in the code generator?

- `componentsPattern`
- `typesPattern`
- `parserPattern`
- `validatorPattern`

Effectively these methods are getters for static constants such as `PARSER_PATTERN`.
Can we make these constants private? Their content is available through the getters, so it seems no one needs to "see" the constants themselves.

**Comment by zubri** [comment]
Hi,

I agree the constants and getters are redundant. We could preserve only the methods. For the constants removal we have to go with the full deprecation cycle since they are now public.

As for the inheritance what's the limitation you are facing? O what's the specific inheritance use case that cannot be achieve.

https://github.com/prowide/prowide-core/blob/develop/src/test/java/com/prowidesoftware/swift/issues/Issue95.java

**Comment by zubri** [comment]
We could keep just the methods, protected, in the major release. Since removing now the public static constants would be a breaking change. Anyway a few remarks:

- Changing the pattern would not automatically make the parser behave differently, since the parse code is hardcoded during code generation. I don't see the benefit of changing these dynamically in a subclass.
- If this content for this particular field is a common/standard situation we could just add more API to the Field24D class to break that second component into two parts.

**Comment by sman-81** [comment]
I totally agree about applying the prowide deprecation cycle when changing the API.
Whether the variant of field `Field24D` I have encountered is standard or not I cannot say for sure. My feeling is, it is rather proprietary.
The methods would need to be remain public but be made non-final in my thinking.

**Comment by zubri** [comment]
Change is done. However, notice overwriting the pattern getters will not have any real effect on the field behavior.

**Comment by sman-81** [comment]
Thanks, I am looking forward to this in the next release.

**Comment by zubri** [comment]
release done
